FROM tiangolo/uvicorn-guvicorn:python3.11-slim

SHELL ["/bin/bash", "-c"]

ARG UID
ARG USERNAME
ARG GROUPNAME
RUN groupadd -g ${GID} ${GROUPNAME} && useradd -m -s /bin/bash -u ${UID} -g ${GID} ${USERNAME}

ARG DEBIAN_FRONTEND=noninteractive

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUTEF8=1 \
    PIP_NO_CACHE_DIR=off

# COPY sources.list /etc/apt/sources.list

RUN apt-get update \
    && apt-get install --assume-yes --no-install-recommends \
    docker.io \
    nano \
    sudo

WORKDIR /api

COPY ./requirements.txt ./

RUN python --version \
    python -m venv --help \
    python -m venv .venv \
    source .venv/bin/activate && \
    pip install -upgrade pip && \
    pip install --trusted-host pypi.python.org -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "3000"]
